import MySQLdb as db
import requests
import json
from random import randint
from passlib.apache import HtpasswdFile
import os.path
import os
import socket

def handle_session(requset_for,site_name,roll_no):
		s = requests.Session()
		url = site_name
		if requset_for == "set":
				s.get(url+"/cookies/set/sessioncookie/"+roll_no)
				return s.cookies
		else:
				s.config['keep_alive'] = False




def add_user(username,password):
		cwd = os.path.abspath(__file__)[:-8]
		if os.path.exists(cwd+"login/.htpasswd") == False:
				ht = HtpasswdFile(cwd+"login/.htpasswd", new=True)
				result = ht.set_password(username, password)
				ht.save()
				return result
		else:
				ht = HtpasswdFile(cwd+"login/.htpasswd")
				result = ht.set_password(username, password)
				ht.save()
				if result == False:
						return True

def check_user_password_htpasswd(username,password):
		cwd = os.path.abspath(__file__)[:-8]
		ht = HtpasswdFile(cwd+"login/.htpasswd")
		return ht.check_password(username, password)

def staff_check_user_password_htpasswd(username,password):
		cwd = os.path.abspath(__file__)[:-8]
		ht = HtpasswdFile(cwd+"login/.staff.htpasswd")
		return ht.check_password(username, password)

def get_db_connection(database_name):
		database = db.connect('localhost','root','S',database_name)
		return database, database.cursor()

def login(data):
		data_dict = json.loads(data)
		site_name = data_dict["site-name"]
		roll_no = data_dict["rollno"]
		password = data_dict["password"]
		login_data = {'username': roll_no,'status': 'loggedIn'}
		query = "select password from userPassword where userId = '"+roll_no+"';"
		result = perform_sql_action("applicationProcess",query,'select')
		if False:# result == ():
				return "roll no. doesn't exist..! please signup to continue"
		elif True:# result[0][0] == password:
				if check_user_password_htpasswd(roll_no,password):
						#s = requests.Session()
						#s.get("http://"+site_name+"/cookies/set/sessioncookie/"+roll_no)
						#r = s.get("http://"+site_name+"/cookies")
						#return (r.text) 
						return "True"
				else:
						return "invalid password"

		else:
				return "invalid password"


def validate_pin(data):
		data_dict = json.loads(data)
		pin = data_dict["pin"]
		roll_no = data_dict["roll_no"]
		new_pass = data_dict["new_password"]
		query = "SELECT userId FROM userIdDomain WHERE userId = '"+ roll_no +"';"
		result = perform_sql_action("applicationProcess",query,'select')
		if len(result) == 1:
				if is_valid_pin(data):
						add_user(roll_no,new_pass)
						query = "insert into inputRequests(requestTime,requestType,userId,tableId,params) values(NOW(),'insert','" + roll_no + "','userPassword','"+ new_pass +"');"
						ret = perform_sql_action("applicationProcess",query, 'insert')
						query = "delete from applicationProcess.applicationCodeBySystem where userId = " + roll_no + ";"
						perform_sql_action("applicationProcess",query, 'delete')

						return "new_password,success"
				else:
						return "pin,invalid," + pin
		else:
				return "rollno,invalid," + roll_no

def perform_sql_action(database_name,query, action):
		try:
				db_con, db_cur = get_db_connection(database_name)
				db_cur.execute(query)
				if(action == 'select'):
						result = db_cur.fetchall()
						db_cur.close()
						return result
				else:
						db_con.commit()
						db_con.close()
		except Exception as e:
				return "DatabaseError, "+str(e)




def is_valid_pin(data):
		data_dict = json.loads(data);
		roll_no  = data_dict["roll_no"]
		pin = data_dict["pin"];
		query = "select applicationCode from applicationProcess.applicationCodeBySystem where userId = '" + roll_no +"';"
		result = perform_sql_action("applicationProcess",query,"select")
		if result[0][0] == pin:
				return True
		else:
				return False


def forgot_password(data):
		data_dict = json.loads(data)
		roll_no = data_dict["roll_no"]
		random_number = str(randint(1000000, 9999999))
		query = "insert into inputRequests(requestTime,requestType,userId,tableId,params) values (NOW(),'insert','"+roll_no +"','applicationCodeBySystem', '"+ random_number+"')"
		result = perform_sql_action("userInputDatabase",query,"insert");
		return "True"


def get_student_reset_code(data):
		data_dict = json.loads(data)
		roll_no = data_dict["rollno"]
		query = "select applicationCode from applicationProcess.applicationCodeBySystem where userId = '" + roll_no + "';"
		result = perform_sql_action("applicationProcess",query,"select")
		if result == ():
				return "PIN request NOT generated by student"
		return "reset pin is "+ str(result[0][0])

def signup_pin_generator(data):
		data_dict = json.loads(data)
		roll_no = data_dict["roll_no"]
		random_number = str(randint(1000000, 9999999))
		query = "select '"+ roll_no +"' in (select userId from applicationProcess.userIdDomain where userId = '"+ roll_no +"');"
		result = perform_sql_action("applicationProcess",query,"select");
		if int(result[0][0]) == 1:
				query = "insert into inputRequests(requestTime,requestType,userId,tableId,params) values (NOW(),'insert','"+roll_no +"','applicationCodeBySystem', '" + random_number +"')"
				result = perform_sql_action("userInputDatabase",query,"insert");
				return "True"
		else:
				return "False"

def old_staff_login(data):
		data_dict = json.loads(data)
		staff_username = data_dict["username"]
		staff_password = data_dict["password"]
		query = "select userId from applicationProcess.userPassword where userId = '"+staff_username+"'";
		result = perform_sql_action("applicationProcess",query,"select");
		try:
				if result[0][0] == staff_username:
						query = "select password from applicationProcess.userPassword where userId = '"+staff_username+"'";
						result = perform_sql_action("applicationProcess",query,"select");
						if result[0][0] == staff_password:
								return "True"
						else:
								return "False"
				else:
						return "False"
		except IndexError:
				return "user dosent signed in please check login details"


def staff_login(data):
		data_dict = json.loads(data)
		staff_username = data_dict["username"]
		staff_password = data_dict["password"]
		if staff_check_user_password_htpasswd(staff_username,staff_password):
				return "True"
		else:
				return "Invalid Login Details"
